### ISSUE TITLE
在 mac 下会执行 gulp 命令的时候会报错说 node-sass 不支持当前 Mac 环境

### ISSUE THREAD

**Issue by wuxiaolan91** [Lxxyx/LxxyxResume#4]
1. 开发环境: Mac 64位
2. 报错的具体信息:
/Users/wxl/Documents/github/testResume/LxxyxResume/node_modules/node-sass/lib/binding.js:13
throw new Error(errors.unsupportedEnvironment());
^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
at module.exports (/Users/wxl/Documents/github/testResume/LxxyxResume/node_modules/node-sass/lib/binding.js:13:13)
at Object.<anonymous> (/Users/wxl/Documents/github/testResume/LxxyxResume/node_modules/node-sass/lib/index.js:14:35)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/Users/wxl/Documents/github/testResume/LxxyxResume/node_modules/gulp-sass/index.js:187:21)
wuxiaolandeMacBook-Pro:LxxyxResume wxl$
3. 报错的解决办法
这个报错是说  gulp-sass 会调用 node-sass, 而no-sass 不支持当前环境:OS X 64-bit
可以通过执行` npm install node-sass --save-dev`来解决

**Comment by Lxxyx** [comment]
已升级gulp-sass版本，应该已经解决你的问题了
